### ISSUE TITLE
Kalender Sync funktioniert nicht

### ISSUE THREAD

**Issue by Om3gaOfficial** [NerLOR/tucal#4]
Mir ich letztes aufgefallen dass das Syncen nicht mehr funktioniert. Er bekommt keinen Job in der URL.
Liegt das an mir?

![image](https://github.com/NerLOR/tucal/assets/59708110/c7f51403-94ec-41a2-9b5e-4d12d754c7e3)

**Comment by NerLOR** [comment]
Danke für den Hinweis. Sollte jetzt wieder funktionieren!
